# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'fott' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fott
  pod 'ObjectMapper+Realm'
  pod 'Alamofire', '~> 4.3.0'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  
  target 'fottTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fottUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
